name = 'bare'
description = 'bare theme'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/cotsuka/cotsuka.github.io'

# If you have a running demo of the theme
demosite = 'https://otsuka.haus'

# Taxonomy terms
tags = ['blog', 'personal', 'responsive']
features = ['minimal', 'rss']

# If the theme has a single author
[author]
  name = 'Cameron Otsuka'
  homepage = 'https://otsuka.haus'